version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOCKER_USER:
    secure: +T9MYtYwml5+Jnd8UXjbcw==
  DOCKER_PWD:
    secure: dLAC65xtVk0CENk9iiIz4A==
build_script:
  - dotnet --info
  - dotnet publish -o ./publish WebAppWithDocker.sln
  - docker info
  - docker build -t samisq/test-ci .
deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push samisq/test-ci