version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: dotnet --info
- cmd: systeminfo
- docker info
- ps: Get-CimInstance -ClassName Win32_OperatingSystem
environment:
  DOCKER_USER:
    secure: +T9MYtYwml5+Jnd8UXjbcw==
  DOCKER_PASS:
    secure: dLAC65xtVk0CENk9iiIz4A==
build_script:
  - dotnet publish -o ./publish WebAppWithDocker.sln
  - docker build -t samisq/test-ci:%APPVEYOR_BUILD_NUMBER% .
deploy_script:
  - echo "%DOCKER_USER%"
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - docker push samisq/test-ci